test_task/menu/urls.py
from django.urls import path

from . import views

app_name = 'menu'

urlpatterns = [
    path('', views.index, name='index'),
    path('<slug:menu_slug>/', views.menu, name='menu'),
    path('<slug:menu_slug>/<slug:fl_slug>/', views.first, name='fl'),
    path(
        '<slug:menu_slug>/<slug:fl_slug>/<slug:sl_slug>/',
        views.second, name='sl'
    ),
    path(
        '<slug:menu_slug>/<slug:fl_slug>/<slug:sl_slug>/<slug:tl_slug>/',
        views.third, name='tl'
    ),
]

test_task/test_task/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('menu.urls', namespace='menu')),
    path('admin/', admin.site.urls),
]

test_task/menu/models.py
from django.db import models

class Menu(models.Model):
    """Модель меню."""
    name = models.CharField(
        verbose_name='Название',
        max_length=100,
    )
    slug = models.SlugField(
        unique=True,
        verbose_name='Уникальное обозначение',
    )

    class Meta:
        verbose_name = 'Меню'
        verbose_name_plural = 'Меню'

    def __str__(self):
        """Вывод названия меню."""
        return self.name


class FirstLevel(models.Model):
    """Список первого уровня."""
    name = models.CharField(
        verbose_name='Название',
        max_length=100,
    )
    slug = models.SlugField(
        unique=True,
        verbose_name='Уникальное обозначение',
    )
    menu = models.ForeignKey(
        Menu,
        on_delete=models.CASCADE,
        related_name='first_level',
        verbose_name='Меню',
    )

    class Meta:
        verbose_name = 'Первый уровень'
        verbose_name_plural = 'Первые уровни'

    def __str__(self):
        """Вывод названия."""
        return self.name


class SecondLevel(models.Model):
    name = models.CharField(
        verbose_name='Название',
        max_length=100,
    )
    slug = models.SlugField(
        unique=True,
        verbose_name='Уникальное обозначение',
    )
    first_level = models.ForeignKey(
        FirstLevel,
        on_delete=models.CASCADE,
        related_name='second_level',
        verbose_name='Первый уровень',
    )

    class Meta:
        verbose_name = 'Второй уровень'
        verbose_name_plural = 'Вторые уровни'

    def __str__(self):
        """Вывод названия."""
        return self.name

class ThirdLevel(models.Model):
    name = models.CharField(
        verbose_name='Название',
        max_length=100,
    )
    slug = models.SlugField(
        unique=True,
        verbose_name='Уникальное обозначение',
    )
    second_level = models.ForeignKey(
        SecondLevel,
        on_delete=models.CASCADE,
        related_name='third_level',
        verbose_name='Первый уровень',
    )

    class Meta:
        verbose_name = 'Третий уровень'
        verbose_name_plural = 'Третьи уровни'

    def __str__(self):
        """Вывод названия."""
        return self.name

test_task/menu/views.py
from django.shortcuts import get_object_or_404,render

from .models import Menu, FirstLevel, SecondLevel, ThirdLevel


def index(request):
    """Настройка отображения главной страницы."""
    menus = Menu.objects.all()
    context = {
        'menus': menus,
    }
    template = 'menu/index.html'

    return render(request, template, context)

def menu(request, menu_slug):
    menu = get_object_or_404(
        Menu.objects.select_related(),
        slug=menu_slug
    )

    context = {
        'menu': menu,
    }
    template = 'menu/menu.html'

    return render(request, template, context)

def first(request, menu_slug, fl_slug):
    menu = get_object_or_404(
        Menu.objects.select_related(),
        slug=menu_slug
    )
    first = menu.first_level.get(
        slug=fl_slug
    )

    context = {
        'menu': menu,
        'first': first,
    }
    template = 'menu/menu.html'

    return render(request, template, context)

def second(request, menu_slug, fl_slug, sl_slug):
    menu = get_object_or_404(
        Menu.objects.select_related(),
        slug=menu_slug
    )
    second = menu.first_level.get(slug=fl_slug).second_level.get(
        slug=sl_slug
    )


    context = {
        'menu': menu,
        'second': second,
    }
    template = 'menu/menu.html'

    return render(request, template, context)

def third(request, menu_slug, fl_slug, sl_slug, tl_slug):
    menu = get_object_or_404(
        Menu.objects.select_related(),
        slug=menu_slug
    )
    third = menu.first_level.get(slug=fl_slug).second_level.get(
        slug=sl_slug
    ).third_level.get(slug=tl_slug)


    context = {
        'menu': menu,
        'third': third,
    }
    template = 'menu/menu.html'

    return render(request, template, context)

test_task/templates/menu/index.html
<body>
  <header>
    <a class="button" href="{% url 'menu:index' %}">
    Список меню</a>
  </header>
  <main> 
    {% for menu in menus %}
      <a href="{% url 'menu:menu' menu.slug %}"> {{ menu.name }} </a>
      <br>
    {% endfor %}
  </main>
</body>

test_task/templates/menu/menu.html
{% load tags %}
{% load static %}
<head>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
    <header>
        <a class="button" href="{% url 'menu:index' %}">
        Список меню</a>
    </header>
    <main>
        <h2>{{menu.name}}</h2>
        {% draw_menu menu.slug request.path %}
    </main>
</body>

test_task/templates/menu/menu_detail.html
<ul class="nav flex-column nav-pills">
    {% for first in menu.first_level.all %}
      <a class="nav-link 
      {% if url  == first.slug %}active{% endif %}
      " href="{% url 'menu:fl' menu.slug first.slug %}">
        {{ first.name }}
      </a>
      {% for second in first.second_level.all %}
        <a class="nav-link
        {% if url  == second.slug %}active{% endif %}
        " href="{% url 'menu:sl' menu.slug first.slug second.slug %}">
          --{{ second.name }}
        </a>
        {% for third in second.third_level.all %}
        <a class="nav-link 
        {% if url  == third.slug %}active{% endif %}
        " href="{% url 'menu:tl' menu.slug first.slug second.slug third.slug %}">
          ----{{ third.name }}
        </a>
      
        {% endfor %}
      {% endfor %}
    {% endfor %}
</ul>